### ISSUE TITLE
Having some troubles making the project

### ISSUE THREAD

**Issue by CapitanLiteral** [VirtuosoChris/VirtuosoConsole#1] opened 2017-07-06 19:00 UTC
Hi, I'm tring to run your test but it gives me this error message:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "private: void __thiscall Virtuoso::GameConsole::dereferenceVariables(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?dereferenceVariables@GameConsole@Virtuoso@@AAEXAAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "public: void __thiscall Virtuoso::GameConsole::commandExecute(class std::basic_istream<char,struct std::char_traits<char> > *)" (?commandExecute@GameConsole@Virtuoso@@QAEXPAV?$basic_istream@DU?$char_traits@D@std@@@std@@@Z)	ConsoleTest	VirtuosoConsole.lib(GameConsole.obj)`

And I dont know how to deal with it...

Help will be apreciated, I'm a newbie in C++ world.

**Comment by VirtuosoChris** [comment] 2017-07-07 06:36
Hi, 
I had some bugs with the ifdefs ("HISTORY_FILE") when boost isn't found in cmake.  This should be fixed with the latest commit.  Thanks for catching that.  The only reason boost is needed is for the history buffer so I can press up and get prior commands in my engine ~ I dislike the dependency for such a minor feature and will probably be replacing that with a different data structure in a future patch.  I tested the test program and everything appeared to work; You should be good to go for now, let me know if you have any more troubles.  I'll have to make time to check out the engine on your page :)

**Comment by VirtuosoChris** [comment] 2017-07-07 07:26
> I dislike the dependency for such a minor feature and will probably be replacing that with a different data structure in a future patch. 

...and done!

**Comment by VirtuosoChris** [comment] 2017-07-07 07:27
Repro'd the issue and fixed on my end.  Reopen the issue or contact me directly if the issue isn't now resolved.

**Closed as completed by VirtuosoChris** 2017-07-07 07:27 UTC
